const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const bg=document.getElementById('space'),bc=bg.getContext('2d'),burst=document.getElementById('burst'),cx=burst.getContext('2d');let w,h,dpr,stars=[],particles=[],running=false,audioOn=false,ac;
function resize(){w=innerWidth;h=innerHeight;dpr=Math.min(devicePixelRatio||1,2);for(const c of [bg,burst]){c.width=w*dpr;c.height=h*dpr;c.getContext('2d').setTransform(dpr,0,0,dpr,0,0)}stars=Array.from({length:75},()=>({x:Math.random()*w,y:Math.random()*h,r:Math.random()*1.3+.3,p:Math.random()*6.28,v:Math.random()*.12+.04}))}resize();addEventListener('resize',resize);
function ambient(t){bc.clearRect(0,0,w,h);for(const s of stars){bc.globalAlpha=.3+Math.sin(t*.0007+s.p)*.25;bc.fillStyle='#ff6c80';bc.beginPath();bc.arc(s.x,s.y,s.r,0,Math.PI*2);bc.fill();if(!reduced){s.y-=s.v;if(s.y<0)s.y=h}}bc.globalAlpha=1;if(!reduced)requestAnimationFrame(ambient)}ambient(0);
function drawStar(x,y,r,angle,color,alpha){cx.save();cx.translate(x,y);cx.rotate(angle);cx.globalAlpha=alpha;cx.fillStyle=color;cx.shadowColor='#ff163e';cx.shadowBlur=12;cx.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,k=i%2?r*.43:r;cx.lineTo(Math.cos(a)*k,Math.sin(a)*k)}cx.closePath();cx.fill();cx.restore()}
let last=0;function animate(t){const dt=Math.min((t-last)/16.67||1,2);last=t;cx.clearRect(0,0,w,h);particles=particles.filter(p=>p.life>0);for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=.11*dt;p.vx*=.994;p.rot+=p.spin*dt;p.life-=dt;drawStar(p.x,p.y,p.r,p.rot,p.color,Math.min(1,p.life/35))}if(particles.length)requestAnimationFrame(animate);else{running=false;cx.clearRect(0,0,w,h)}}
function sound(){if(!audioOn)return;try{ac||=new (window.AudioContext||window.webkitAudioContext)();ac.resume();const now=ac.currentTime;[130.81,196,261.63,392].forEach((f,i)=>{const o=ac.createOscillator(),g=ac.createGain();o.type='sine';o.frequency.setValueAtTime(f,now+i*.045);o.frequency.exponentialRampToValueAtTime(f*2,now+.45);g.gain.setValueAtTime(0,now);g.gain.linearRampToValueAtTime(.07,now+i*.045+.015);g.gain.exponentialRampToValueAtTime(.001,now+.75);o.connect(g);g.connect(ac.destination);o.start(now);o.stop(now+.8)})}catch{}}
const vote=document.getElementById('vote');vote.addEventListener('click',()=>{const b=vote.getBoundingClientRect(),x=b.left+b.width/2,y=b.top+b.height/2;const count=reduced?25:190;for(let i=0;i<count;i++){let a=Math.random()*Math.PI*2,s=3+Math.random()*16;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-5,r:4+Math.random()*15,rot:Math.random()*6,spin:(Math.random()-.5)*.18,life:60+Math.random()*100,color:['#ff243f','#ff4960','#e9092c','#ff6b78'][i%4]})}if(particles.length>700)particles=particles.slice(-700);const flash=document.getElementById('flash');flash.classList.remove('active');void flash.offsetWidth;if(!reduced)flash.classList.add('active');document.getElementById('hint').textContent='As estrelas já deram o recado.';sound();if(!running){running=true;last=performance.now();requestAnimationFrame(animate)}});
document.querySelector('.sound').addEventListener('click',function(){audioOn=!audioOn;this.setAttribute('aria-pressed',String(audioOn));this.setAttribute('aria-label',audioOn?'Desativar som':'Ativar som');this.querySelector('span').textContent=audioOn?'ON':'OFF';if(audioOn)sound()});
const photo=document.getElementById('photo'),cursor=document.querySelector('.cursor');if(!reduced&&matchMedia('(pointer:fine)').matches){addEventListener('pointermove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'});photo.addEventListener('pointermove',e=>{const r=photo.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;photo.style.transform=`rotate(-3deg) rotateY(${x*9}deg) rotateX(${-y*9}deg)`});photo.addEventListener('pointerleave',()=>photo.style.transform='rotate(-3deg)')}
